// <auto-generated />
namespace OpenData.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class mgr3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mgr3));
        
        string IMigrationMetadata.Id
        {
            get { return "201310280719316_mgr3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
