// <auto-generated />
namespace OpenData.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class m18 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(m18));
        
        string IMigrationMetadata.Id
        {
            get { return "201312131304491_m18"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
