// <auto-generated />
namespace OpenData.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class mgr4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mgr4));
        
        string IMigrationMetadata.Id
        {
            get { return "201310281039324_mgr4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
